# Generated by Django 4.1 on 2022-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='entry_num',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
