# Generated by Django 4.1 on 2022-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_entry_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('1', 'available'), ('2', 'booked'), ('3', 'cancelled')], default='1', max_length=1),
        ),
    ]
