# Generated by Django 4.1 on 2022-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_slot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='members',
            field=models.ManyToManyField(to='accounts.member'),
        ),
    ]
