# Generated by Django 4.1 on 2022-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_slot_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='slots',
            field=models.ManyToManyField(to='accounts.slot'),
        ),
    ]
