# Generated by Django 4.1 on 2022-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_slot_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='capacity',
        ),
        migrations.AddField(
            model_name='court',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
